import type {
  AidRequest,
  AppNotification,
  Donation,
  EmergencyDrive,
  User,
} from "./types"

const now = Date.now()
const hr = 3600 * 1000
const day = 24 * hr

const DEFAULT_MOCK_PASSWORD_HASH = "$2b$10$LGY2i5cMTrooK5SIO41h9uAa.hSVrmBeCq64e4rEHR6ufTk4qy9wC"

export const USERS: User[] = [
  {
    id: "u-admin",
    name: "Amara Okafor",
    email: "admin@essentialaid.org",
    phone: "+1-512-555-0101",
    password: DEFAULT_MOCK_PASSWORD_HASH,
    emailVerified: true,
    phoneVerified: true,
    roles: ["admin"],
    location: "Central Relief HQ, Austin TX",
    coords: { lat: 30.2672, lng: -97.7431 },
  },
  {
    id: "u-donor",
    name: "Daniel Reyes",
    email: "donor@essentialaid.org",
    phone: "+1-512-555-0102",
    password: DEFAULT_MOCK_PASSWORD_HASH,
    emailVerified: true,
    phoneVerified: true,
    roles: ["donor"],
    location: "North Austin, TX",
    coords: { lat: 30.4, lng: -97.72 },
  },
  {
    id: "u-recipient",
    name: "Fatima Hassan",
    email: "recipient@essentialaid.org",
    phone: "+1-512-555-0103",
    password: DEFAULT_MOCK_PASSWORD_HASH,
    emailVerified: true,
    phoneVerified: true,
    roles: ["recipient"],
    location: "East Austin, TX",
    coords: { lat: 30.26, lng: -97.68 },
  },
  {
    id: "u-logistics",
    name: "Leo Martins",
    email: "logistics@essentialaid.org",
    phone: "+1-512-555-0104",
    password: DEFAULT_MOCK_PASSWORD_HASH,
    emailVerified: true,
    phoneVerified: true,
    roles: ["logistics"],
    location: "Dispatch Center, Austin TX",
    coords: { lat: 30.29, lng: -97.75 },
  },
  {
    id: "u-volunteer",
    name: "Elena Rostova",
    email: "volunteer@essentialaid.org",
    phone: "+1-512-555-0105",
    password: DEFAULT_MOCK_PASSWORD_HASH,
    emailVerified: true,
    phoneVerified: true,
    roles: ["volunteer"],
    location: "South Congress, Austin TX",
    coords: { lat: 30.24, lng: -97.75 },
  },
]

export const DRIVES: EmergencyDrive[] = [
  {
    id: "drive-flood",
    title: "Hill Country Flood Relief",
    description:
      "Flash flooding has displaced hundreds of families. Urgent need for clean water, bedding, and medical supplies.",
    location: "Kerr County, TX",
    categories: ["Food & Water", "Shelter & Bedding", "Medical Supplies"],
    active: true,
    createdAt: now - 2 * day,
    goal: 500,
  },
  {
    id: "drive-heat",
    title: "Summer Heat Emergency",
    description: "Record temperatures. Collecting fans, electrolytes, and water for vulnerable residents.",
    location: "Travis County, TX",
    categories: ["Food & Water", "Electronics", "Medical Supplies"],
    active: true,
    createdAt: now - 5 * day,
    goal: 300,
  },
]

export const DONATIONS: Donation[] = [
  {
    id: "d-1001",
    donorId: "u-donor",
    donorName: "Daniel Reyes",
    category: "Food & Water",
    title: "Bottled water (24-pack cases)",
    quantity: 40,
    condition: "New",
    pickupLocation: "North Austin, TX",
    coords: { lat: 30.4, lng: -97.72 },
    status: "In-transit",
    verified: true,
    autoVerified: true,
    driveId: "drive-flood",
    matchedRequestId: "r-2001",
    matchConfidence: 92,
    pickupMethod: "Volunteer delivery",
    deliveryWindow: "Today, 2:00 PM - 4:00 PM",
    createdAt: now - 3 * day,
    history: [
      { status: "Listed", at: now - 3 * day },
      { status: "Verified", at: now - 3 * day + 2 * hr, note: "Auto-verified" },
      { status: "Matched", at: now - 2 * day, note: "Matched to critical request" },
      { status: "Picked-up", at: now - hr * 6 },
      { status: "In-transit", at: now - hr * 2 },
    ],
  },
  {
    id: "d-1002",
    donorId: "u-donor",
    donorName: "Daniel Reyes",
    category: "Clothing",
    title: "Winter jackets, assorted sizes",
    quantity: 25,
    condition: "Good",
    pickupLocation: "North Austin, TX",
    coords: { lat: 30.4, lng: -97.72 },
    status: "Listed",
    verified: false,
    autoVerified: false,
    createdAt: now - 6 * hr,
    history: [{ status: "Listed", at: now - 6 * hr }],
  },
  {
    id: "d-1003",
    donorId: "u-2",
    donorName: "Priya Nair",
    category: "Medical Supplies",
    title: "First-aid kits, sealed",
    quantity: 15,
    condition: "New",
    pickupLocation: "South Austin, TX",
    coords: { lat: 30.2, lng: -97.78 },
    status: "Verified",
    verified: true,
    autoVerified: false,
    driveId: "drive-flood",
    createdAt: now - day,
    history: [
      { status: "Listed", at: now - day },
      { status: "Verified", at: now - 20 * hr, note: "Admin verified after photo review" },
    ],
  },
  {
    id: "d-1004",
    donorId: "u-3",
    donorName: "Marcus Bell",
    category: "Shelter & Bedding",
    title: "Emergency blankets & sleeping bags",
    quantity: 60,
    condition: "New",
    pickupLocation: "Round Rock, TX",
    coords: { lat: 30.51, lng: -97.68 },
    status: "Delivered",
    verified: true,
    autoVerified: true,
    driveId: "drive-flood",
    matchedRequestId: "r-2003",
    matchConfidence: 88,
    pickupMethod: "Third-party courier",
    deliveryWindow: "Yesterday, 10:00 AM - 12:00 PM",
    createdAt: now - 4 * day,
    history: [
      { status: "Listed", at: now - 4 * day },
      { status: "Verified", at: now - 4 * day + hr },
      { status: "Matched", at: now - 3 * day },
      { status: "Picked-up", at: now - 2 * day },
      { status: "In-transit", at: now - 30 * hr },
      { status: "Delivered", at: now - 26 * hr },
    ],
  },
  {
    id: "d-1005",
    donorId: "u-4",
    donorName: "Sofia Lin",
    category: "Baby & Child",
    title: "Diapers, formula & baby wipes",
    quantity: 30,
    condition: "New",
    pickupLocation: "Cedar Park, TX",
    coords: { lat: 30.5, lng: -97.82 },
    status: "Matched",
    verified: true,
    autoVerified: true,
    matchedRequestId: "r-2002",
    matchConfidence: 76,
    createdAt: now - 2 * day,
    history: [
      { status: "Listed", at: now - 2 * day },
      { status: "Verified", at: now - 2 * day + hr },
      { status: "Matched", at: now - hr * 8 },
    ],
  },
  {
    id: "d-1006",
    donorId: "u-5",
    donorName: "Grace Kim",
    category: "Hygiene",
    title: "Hygiene kits (soap, toothpaste, towels)",
    quantity: 50,
    condition: "New",
    pickupLocation: "Pflugerville, TX",
    coords: { lat: 30.44, lng: -97.62 },
    status: "Reviewed",
    verified: true,
    autoVerified: true,
    matchedRequestId: "r-2004",
    matchConfidence: 81,
    pickupMethod: "Self-pickup",
    deliveryWindow: "2 days ago",
    createdAt: now - 6 * day,
    rating: 5,
    feedback: "Arrived quickly and everything was in perfect condition. Thank you!",
    history: [
      { status: "Listed", at: now - 6 * day },
      { status: "Verified", at: now - 6 * day + hr },
      { status: "Matched", at: now - 5 * day },
      { status: "Picked-up", at: now - 4 * day },
      { status: "In-transit", at: now - 3 * day },
      { status: "Delivered", at: now - 2 * day },
      { status: "Reviewed", at: now - day, note: "5-star review left" },
    ],
  },
]

export const REQUESTS: AidRequest[] = [
  {
    id: "r-2001",
    recipientId: "u-recipient",
    recipientName: "Fatima Hassan",
    category: "Food & Water",
    quantity: 30,
    urgency: "Critical",
    deliveryAddress: "East Austin, TX",
    coords: { lat: 30.26, lng: -97.68 },
    status: "Matched",
    matchedDonationId: "d-1001",
    driveId: "drive-flood",
    createdAt: now - 2 * day,
  },
  {
    id: "r-2002",
    recipientId: "u-recipient",
    recipientName: "Fatima Hassan",
    category: "Baby & Child",
    quantity: 20,
    urgency: "High",
    deliveryAddress: "East Austin, TX",
    coords: { lat: 30.26, lng: -97.68 },
    status: "Matched",
    matchedDonationId: "d-1005",
    createdAt: now - 9 * hr,
  },
  {
    id: "r-2003",
    recipientId: "u-6",
    recipientName: "Omar Said",
    category: "Shelter & Bedding",
    quantity: 40,
    urgency: "Critical",
    deliveryAddress: "Kerrville, TX",
    coords: { lat: 30.05, lng: -99.14 },
    status: "Delivered",
    matchedDonationId: "d-1004",
    driveId: "drive-flood",
    createdAt: now - 3 * day,
  },
  {
    id: "r-2004",
    recipientId: "u-7",
    recipientName: "Elena Volkov",
    category: "Hygiene",
    quantity: 35,
    urgency: "Normal",
    deliveryAddress: "Georgetown, TX",
    coords: { lat: 30.63, lng: -97.68 },
    status: "Reviewed",
    matchedDonationId: "d-1006",
    createdAt: now - 6 * day,
    rating: 5,
    feedback: "Incredibly grateful for the quick help.",
  },
  {
    id: "r-2005",
    recipientId: "u-8",
    recipientName: "James Carter",
    category: "Medical Supplies",
    quantity: 12,
    urgency: "Critical",
    deliveryAddress: "South Austin, TX",
    coords: { lat: 30.21, lng: -97.79 },
    status: "Open",
    driveId: "drive-flood",
    createdAt: now - 4 * hr,
  },
  {
    id: "r-2006",
    recipientId: "u-9",
    recipientName: "Nadia Petrov",
    category: "Clothing",
    quantity: 20,
    urgency: "High",
    deliveryAddress: "North Austin, TX",
    coords: { lat: 30.41, lng: -97.71 },
    status: "Open",
    createdAt: now - 7 * hr,
  },
]

export const NOTIFICATIONS: AppNotification[] = [
  {
    id: "n-1",
    title: "Donation in transit",
    message: "Your bottled water donation is on the way to Fatima H. (Critical request).",
    type: "status",
    urgent: true,
    read: false,
    createdAt: now - 2 * hr,
    role: "donor",
  },
  {
    id: "n-2",
    title: "New emergency drive",
    message: "Hill Country Flood Relief is now active. Urgent need for water and bedding.",
    type: "drive",
    urgent: true,
    read: false,
    createdAt: now - 2 * day,
  },
  {
    id: "n-3",
    title: "Match confirmed",
    message: "First-aid kits from Priya N. matched to a critical medical request.",
    type: "match",
    urgent: false,
    read: true,
    createdAt: now - 20 * hr,
    role: "admin",
  },
]
